apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mobile-cloud-system
data:
  app_env: "production"
  log_level: "INFO"
  max_data_size: "5000"
  min_delay: "0.1"
  max_delay: "1.5"
  cors_origin: "*"
