FROM python:3.12-slim AS builder

WORKDIR /install
COPY Lab3/requirements.txt .
RUN pip install --prefix=/install -r requirements.txt

FROM python:3.12-slim

WORKDIR /app
COPY --from=builder /install /usr/local
COPY Lab3/app.py .

EXPOSE 5000

CMD ["python", "app.py"]
